package com.aashdit.digiverifier.common.enums;

public enum ContentSubCategory {
	AADHAR,
	PAN,
	UAN,
	DRIVING_LICENSE,
	DEGREE_CERTIFICATE,
	RESUME,
	PRE_APPROVAL,
	FINAL,
	INTERIM,
	PROVISIONAL_DEGREE_CERTIFICATE,
	SSC_MARKSHEET,
	HSC_MARKSHEET,
	CONVENTIONALINTERIM,
	CONVENTIONALFINAL,
	CONVENTIONALSUPPLEMENTARY
	
}
